Description: "ChangeSet"

Parameters:
  S3BucketName:
    Description: Enter S3 bucket name
    Type: String
  Environment:
    Type: String
    AllowedValues:
     - dev
     - prod
     - qa

Mappings:
  EnvMap:
    dev:
      instanceType: t2.micro
      name: dev
    qa:
      instanceType: t2.medium
      name: qa
    prod:
      instanceType: t2.xlarge
      name: prod

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref S3BucketName
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [EnvMap, !Ref Environment, instanceType]
      ImageId: ami-0715c1897453cabd1
      Tags:
       - Key: "Name"
         Value: !FindInMap [EnvMap, !Ref Environment, name]
 

Outputs:
  BucketName:
    Value: !Ref S3Bucket
